name: ML CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Run training
        run: |
          export PYTHONPATH=$PYTHONPATH:.
          python src/train.py

      - name: Find latest MLflow run
        id: latest_run
        run: |
          # MLflow default experiment folder
          EXP_DIR="mlruns/0"
          # Find latest run folder by modification time
          LATEST_RUN=$(ls -td $EXP_DIR/* | head -1)
          echo "LATEST_RUN=$LATEST_RUN" >> $GITHUB_ENV
          echo "Latest run detected: $LATEST_RUN"

      - name: Upload latest MLflow run
        uses: actions/upload-artifact@v4
        with:
          name: latest-mlflow-run
          path: ${{ env.LATEST_RUN }}

      - name: Upload API model
        uses: actions/upload-artifact@v4
        with:
          name: api-model
          path: api/
